{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "506ecd07-e12f-4eb1-be9d-27bc4ad203ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "\n",
    "# ====================== TITLE ======================\n",
    "st.set_page_config(page_title=\"Kolkata Election Insights\", layout=\"wide\")\n",
    "st.title(\"📊 Kolkata Election Insights (2011-2026)\")\n",
    "st.markdown(\"**Problem 17** | Team Silent Syntax | VIBE-ATHON 2026\")\n",
    "\n",
    "# ====================== DATA ======================\n",
    "data = {\n",
    "    'Year': [2011]*11 + [2016]*11 + [2021]*11 + [2026]*11,\n",
    "    'Constituency': [\"Kolkata Port\",\"Bhabanipur\",\"Rashbehari\",\"Ballygunge\",\"Chowrangee\",\n",
    "                     \"Entally\",\"Beleghata\",\"Jorasanko\",\"Shyampukur\",\"Maniktala\",\"Kashipur-Belgachhia\"]*4,\n",
    "    'Winner_Party': ['AITC']*33 + ['AITC','BJP','BJP','AITC','AITC','AITC','AITC','BJP','BJP','BJP','BJP'],\n",
    "    'Turnout_Percent': [78.5,82.1,79.3,81.2,77.8,76.4,75.9,78.2,77.5,76.8,74.9,\n",
    "                        76.8,79.5,77.2,78.9,75.4,74.1,73.8,76.5,75.9,74.7,73.2,\n",
    "                        69.2,71.5,68.8,70.4,67.9,66.5,67.1,69.3,68.7,67.4,66.8,\n",
    "                        82.4,79.8,81.5,80.2,78.9,77.6,78.3,79.1,78.7,77.9,76.5],\n",
    "    'Margin_Percent': [19.1,36.8,36.8,28.3,25.4,22.1,19.5,24.8,23.6,28.7,21.4,\n",
    "                       16.3,18.4,10.6,9.9,12.5,15.8,16.3,14.2,13.9,18.1,17.6,\n",
    "                       42.8,18.4,15.2,22.1,28.7,25.4,42.8,19.8,21.3,24.6,19.7,\n",
    "                       36.3,10.8,15.0,36.7,22.4,18.9,12.4,8.7,9.2,11.5,14.2]\n",
    "}\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "# ====================== SIDEBAR FILTERS ======================\n",
    "st.sidebar.header(\"Filters\")\n",
    "selected_years = st.sidebar.multiselect(\"Select Years\", [2011,2016,2021,2026], default=[2011,2016,2021,2026])\n",
    "selected_const = st.sidebar.multiselect(\"Select Constituencies\", df['Constituency'].unique(), default=df['Constituency'].unique()[:5])\n",
    "\n",
    "filtered_df = df[df['Year'].isin(selected_years) & df['Constituency'].isin(selected_const)]\n",
    "\n",
    "# ====================== MAIN DASHBOARD ======================\n",
    "col1, col2, col3 = st.columns(3)\n",
    "col1.metric(\"Total Constituencies\", len(selected_const))\n",
    "col2.metric(\"Selected Years\", len(selected_years))\n",
    "col3.metric(\"Avg Turnout\", f\"{filtered_df['Turnout_Percent'].mean():.1f}%\")\n",
    "\n",
    "# Charts\n",
    "st.subheader(\"1. Voter Turnout Trends\")\n",
    "fig1 = px.line(filtered_df, x='Year', y='Turnout_Percent', color='Constituency', markers=True,\n",
    "               title=\"Turnout Comparison\")\n",
    "st.plotly_chart(fig1, use_container_width=True)\n",
    "\n",
    "st.subheader(\"2. Winning Party Trends\")\n",
    "fig2 = px.imshow(df.pivot(index='Constituency', columns='Year', values='Winner_Party'),\n",
    "                 text_auto=True, title=\"Winning Party Heatmap\")\n",
    "st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "st.subheader(\"3. Major Swings in 2026\")\n",
    "swing_df = df[df['Year'].isin([2021,2026])]\n",
    "st.dataframe(swing_df, use_container_width=True)\n",
    "\n",
    "# Key Insights\n",
    "st.subheader(\"🔥 Key Regional Insights\")\n",
    "st.markdown(\"\"\"\n",
    "- **2011-2021**: Total dominance by AITC (TMC)\n",
    "- **2026**: Major shift — BJP won **5 seats** including Bhabanipur\n",
    "- Turnout was **highest in 2026** → Strong public participation\n",
    "- Central & North Kolkata showed biggest political change\n",
    "\"\"\")\n",
    "\n",
    "st.caption(\"Made for VIBE-ATHON 2026 | Problem 17\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
